groups:
- name: Nextcloud
  rules:
  - alert: Nextcloud App Update available
    expr: nextcloud_apps_updates_available_total > 0
    for: 1d
    labels:
      severity: warning
    annotations:
      summary: Nextcloud app update available
      description: "There are {{ $value }} app updates available.\n  LABELS = {{ $labels }}"
  - alert: New Nextcloud User
    expr: '( sum ( delta ( nextcloud_users_total[5m] ) ) > 0 )'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: New Nextcloud user detected
      description: "{{ $value }} new Nextcloud user detected on {{ $labels.instance }}. If this is expected, you can ignore this message.\n  LABELS = {{ $labels }}"
  - alert: Nextcloud down
    expr: 'nextcloud_up < 1'
    for: 2h
    labels:
      severity: critical
    annotations:
      summary: Nextcloud is not running
      description: "Nextcloud on {{ $labels.instance }} is not reported to be up for at least two hours. If this is expected, you can ignore this message.\n  LABELS = {{ $labels }}"

- name: Nextcloud backup synchronization
  rules:
  - alert: Cloud backup not synchronized
    expr: '(time()-nextcloud_backup_sync_last_run{remote="remote-nc-bkp"}) / 3600 > 28'
    labels:
      severity: warning
    annotations:
      summary: "Nextcloud backup has not been synchronized to remote cloud"
      description: "Nextcloud backup has not been synchronized to remote cloud for {{ $value }} hours. You might want to check why.\n LABELS = {{ $labels }}"
  - alert: Sync external disk backup
    expr: '(time()-nextcloud_backup_sync_last_run{remote="/media/nc-bkp-ext"}) / (3600 * 24) > 28'
    labels:
      severity: information
    annotations:
      summary: "Plug in external disk to Nextcloud server"
      description: "Nextcloud backup has not been synchronized to the external disk for {{ $value }} days. You might want to plug in your disk to the server.\n LABELS = {{ $labels }}"
  - alert: Nextcloud backup size increase
    expr: 'idelta(nextcloud_backup_sync_bytes[1m]) * 100 /nextcloud_backup_sync_bytes offset 1m > 20'
    labels:
      severity: warning
    annotations:
      summary: "Nextcloud backup size increased"
      description: "Nextcloud backup size increased by {{ $value }}%. If this is expected you can ignore this warning.\n LABELS = {{ $labels }}"
  - alert: Nextcloud backup size decrease
    expr: 'idelta(nextcloud_backup_sync_bytes[1m]) * 100 /nextcloud_backup_sync_bytes offset 1m < -20'
    labels:
      severity: warning
    annotations:
      summary: "Nextcloud backup size decreased"
      description: "Nextcloud backup size decreased by {{ $value }}%. If this is expected you can ignore this warning.\n LABELS = {{ $labels }}"