# config file version

apiVersion: 1

# list of datasources that should be deleted from the database

deleteDatasources:

- name: Alertmanager
  orgId: 1

# list of datasources to insert/update depending

# whats available in the database

datasources:

# name of the datasource. Required

- name: Alertmanager
  orgId: 1
  type: alertmanager
  typeName: Alertmanager
  typeLogoUrl: public/app/plugins/datasource/alertmanager/img/logo.svg
  access: proxy
  url: 'http://localhost:9093'
  user: ''
  database: ''
  basicAuth: false
  isDefault: false
  jsonData:
    handleGrafanaManagedAlerts: true
    implementation: prometheus
  readOnly: false