# config file version

apiVersion: 1

# list of datasources that should be deleted from the database

deleteDatasources:

- name: Prometheus
  orgId: 1

# list of datasources to insert/update depending

# whats available in the database

datasources:

# name of the datasource. Required

- name: Prometheus
  orgId: 1
  type: prometheus
  typeName: Prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
  access: proxy
  url: 'http://localhost:9090'
  user: ''
  database: ''
  basicAuth: false
  isDefault: true
  jsonData:
    httpMethod: POST
  readOnly: false